### ISSUE TITLE
SyntaxError in broker.py while creating SQSBroker

### ISSUE THREAD

**Issue by nikochiko** [Bogdanp/dramatiq_sqs#3]
OS: Ubuntu 16.04 Xenial
Python: python 3.5.2

This is the code I'm running:
```python
import dramatiq
import time

from dramatiq.middleware import AgeLimit, TimeLimit, Callbacks, Pipelines, Prometheus, Retries
from dramatiq_sqs import SQSBroker

broker = SQSBroker(
    namespace="dramatiq_sqs_tests",
    middleware=[
        Prometheus(),
        AgeLimit(),
        TimeLimit(),
        Callbacks(),
        Pipelines(),
        Retries(min_backoff=1000, max_backoff=900000, max_retries=96),
    ],
    endpoint_url="http://127.0.0.1:9324",
    region_name="us-east-1",
    aws_access_key_id="x",
    aws_secret_access_key="x",
)
dramatiq.set_broker(broker)
```

This is the error log:
```
nikochiko@ubuntu:~/projects/try-dramatiq$ python demo.py
Traceback (most recent call last):
  File "demo.py", line 5, in <module>
    from dramatiq_sqs import SQSBroker
  File "/usr/local/lib/python3.5/dist-packages/dramatiq_sqs/__init__.py", line 1, in <module>
    from .broker import SQSBroker
  File "/usr/local/lib/python3.5/dist-packages/dramatiq_sqs/broker.py", line 70
    **options,
             ^
SyntaxError: invalid syntax
```

Is anything wrong with the code there?

**Comment by Bogdanp** [comment]
IIRC this is a known issue with a particular version of Python 3.5. You should upgrade to 3.6 or 3.7.
